version: "3.7"
services:
  valheim-server:
    container_name: valheim-server
    build:
      context: /home/valheim/valheim-docker
      dockerfile: docker/Dockerfile.valheim
    restart: always
    stop_signal: SIGINT
    env_file:
      - /home/valheim/valheim-docker/config
    volumes:
      - /home/valheim/server:/valheim-server:ro
      - /home/valheim/data:/valheim-data
      - /home/valheim/logs:/valheim-logs
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
