version: "3.7"
services:
  valheim-server:
    container_name: valheim-server
    build:
      context: .
      dockerfile: Dockerfile.valheim
    restart: always
    environment:
      - SERVER_NAME=IKEA World
      - SERVER_WORLD=Dedicated
      - SERVER_PASSWORD=wootwoot
    volumes:
      - /home/valheim/server:/valheim-server:ro
      - /home/valheim/data:/valheim-data
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
